# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Luzifer / habitscheduler
  description: Schedule your HabitRPG tasks more freely
  version: "0.1.0"
# the domain of the service
host: 127.0.0.1:3000
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /tasks:
    get:
      summary: List scheduled tasks
      produces:
      - application/json
      responses:
        200:
          description: A list of scheduled tasks
          schema:
            type: array
            items:
              $ref: '#/definitions/Task'
    post:
      summary: Create a new scheduled task
      produces:
      - text/plain
      consumes:
      - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Task'
      responses:
        200:
          description: Task was successfully created
        500:
          description: You provided wrong data

  /tasks/{taskId}:
    delete:
      parameters:
        - name: taskId
          in: path
          description: ID of the task to delete
          required: true
          type: string
          pattern: "^[a-z0-9-]+$"
      produces:
        - text/plain
      summary: Delete the task associated with the taskId
      responses:
        200:
          description: Task was successfully deleted
          examples:
            text/plain:
              OK

  /tasks/{taskId}/trigger:
    post:
      parameters:
        - name: taskId
          in: path
          description: ID of the task to delete
          required: true
          type: string
          pattern: "^[a-z0-9-]+$"
      produces:
        - text/plain
      summary: Schedules the next execution date for the task to now
      responses:
        200:
          description: Task was successfully rescheduled
          examples:
            text/plain:
              OK
        404:
          description: Task with {taskId} was not found

definitions:
  Task:
    type: object
    properties:
      ID:
        type: string
        readOnly: true
      Title:
        type: string
      LastTaskID:
        type: string
        readOnly: true
      NextEntryDate:
        type: string
        format: date-time
        readOnly: true
      IsCompleted:
        type: boolean
        readOnly: true
        default: false
      RepeatHours:
        type: integer
        default: 0
      RepeatCron:
        type: boolean
      RepeatCronEntry:
        type: string
    required:
      - Title
      - RepeatCron
    example:
      ID: "1607027b-9321-4273-a0a2-d8fe37b88362"
      Title: "Reload FitBit"
      LastTaskID: ""
      NextEntryDate: "2015-05-31T18:54:10.159Z"
      IsCompleted: true
      RepeatHours: 0
      RepeatCron: true
      RepeatCronEntry: "0 0 8 1,14 * *"
